# Используем официальный образ Nginx
FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf
RUN mkdir -p /etc/nginx
# Копируем конфигурацию Nginx
COPY nginx.conf /etc/nginx/conf.d/nginx.conf
# Открываем порт для Nginx
# EXPOSE 80