services:
  db:
    container_name: app_db
    image: postgres:alpine
    environment:
      - APP_POSTGRES_HOST=localhost
      - APP_POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=123
      - APP_POSTGRES_PASS=123
      - APP_POSTGRES_LOGIN=postgres
      - APP_POSTGRES_DBNAME=library
    healthcheck:
     test: ["CMD-SHELL", "${POSTGRES_USER} -U postgres"]
     interval: 5s
     timeout: 5s
     retries: 5 # That is  five restarts
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
  flask_app:
    container_name: app_lybrary
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: python main.py
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:123@db:5432/lybrary # Замените на ваши данные
    depends_on:
      - db

  nginx:
    container_name: app_nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - flask_app
    restart: on-failure

volumes:
  postgres_data:
    external: true
