services:
  db:
    container_name: app_db
    image: postgres:alpine
    environment:
      ENV APP_POSTGRES_HOST=localhost
      ENV APP_POSTGRES_PORT=5432
      ENV APP_PROTOKOL=http
      ENV APP_POSTGRES_PASS=123
      ENV APP_POSTGRES_LOGIN=postgres
      ENV APP_POSTGRES_DBNAME=library
    volumes:
      - postgres_data:/var/lib/postgresql/data
  flask_app:
    container_name: app_library
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://< Your_login >:< Your_password>@db:5432/lybrary # Замените на ваши данные
    depends_on:
      - db

  nginx:
    container_name: app_nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - flask_app
    restart: on-failure

volumes:
  postgres_data:
    external: true
